# Generated by Django 6.0.7 on 2026-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowaction',
            name='action_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('approve', 'Onayla'), ('reject', 'Reddet'), ('return', 'İade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal')], default='active', max_length=20),
        ),
    ]
