# Generated by Django 6.0.7 on 2026-07-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_workflowaction_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='active', max_length=20),
        ),
    ]
