# Generated by Django 6.0.7 on 2026-07-29 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_alter_workflowinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
