# Generated by Django 6.0.7 on 2026-07-30 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_workflowinstance_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instances', to=settings.AUTH_USER_MODEL, verbose_name='Başlatan'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıklama'),
        ),
    ]
