# Generated by Django 6.0.7 on 2026-07-31 21:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='current_step_entered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Mevcut Adıma Giriş Zamanı'),
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='escalated',
            field=models.BooleanField(default=False, verbose_name='Eskalasyon Yapıldı'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='escalation_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_steps', to='auth.group', verbose_name='Eskalasyon Grubu'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='max_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Beklenen Süre (gün)'),
        ),
    ]
