# Generated by Django 6.0.7 on 2026-08-01 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workflow', '0008_workflowinstance_current_step_entered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDefinitionPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='workflow.workflowdefinition')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definition_permissions', to='auth.group')),
            ],
            options={
                'unique_together': {('group', 'definition')},
            },
        ),
    ]
