# Generated by Django 6.0.7 on 2026-08-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0009_groupdefinitionpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(blank=True, choices=[('approve', 'Onayla'), ('reject', 'Reddet'), ('return', 'İade'), ('cancel', 'İptal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('active', 'Aktif'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Onayla'), ('reject', 'Reddet'), ('return', 'İade'), ('cancel', 'İptal')], max_length=20),
        ),
    ]
